# Generated by Django 4.1 on 2024-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('genero', models.CharField(max_length=128)),
                ('pais_origen', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('ano_lanzamiento', models.IntegerField()),
                ('discografica', models.CharField(max_length=128)),
                ('artistas', models.ManyToManyField(to='musica_api.artista')),
            ],
        ),
    ]
