# Generated by Django 4.1 on 2024-06-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='nombre',
            new_name='name',
        ),
    ]
