# Generated by Django 4.1 on 2024-06-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica_api', '0002_rename_nombre_artista_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='genero',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='ano_lanzamiento',
        ),
        migrations.RemoveField(
            model_name='album',
            name='discografica',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='pais_origen',
        ),
        migrations.AlterField(
            model_name='album',
            name='artistas',
            field=models.ManyToManyField(related_name='albums', to='musica_api.artista'),
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='musica_api.album')),
                ('artistas', models.ManyToManyField(related_name='canciones', to='musica_api.artista')),
            ],
        ),
    ]
